spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet
    username: root
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

